package com.ih.osm.domain.model

data class ProcedimientoCiltData(
    val positions: List<Position>,
) {
    data class Position(
        val id: Int,
        val name: String,
        val siteName: String,
        val areaName: String,
        val ciltMasters: List<CiltMaster>,
    )

    data class CiltMaster(
        val id: Int,
        val siteId: Int,
        val ciltName: String,
        val ciltDescription: String,
        val creatorId: Int,
        val creatorName: String,
        val reviewerId: Int,
        val reviewerName: String,
        val approvedById: Int,
        val approvedByName: String,
        val ciltDueDate: String,
        val standardTime: Int,
        val urlImgLayout: String?,
        val order: Int,
        val dateOfLastUsed: String,
        val createdAt: String,
        val updatedAt: String?,
        val deletedAt: String?,
        val status: String,
        val sequences: List<Sequence>,
    )

    data class Sequence(
        val id: Int,
        val siteId: Int,
        val siteName: String,
        val ciltMstrId: Int,
        val ciltMstrName: String,
        val frecuencyId: Int?,
        val frecuencyCode: String?,
        val ciltTypeId: Int,
        val ciltTypeName: String,
        val secuenceList: String,
        val secuenceColor: String,
        val toolsRequired: String,
        val standardTime: Int,
        val standardOk: String,
        val referenceOplSopId: Int,
        val remediationOplSopId: Int,
        val stoppageReason: Int,
        val machineStopped: Int,
        val quantityPicturesCreate: Int,
        val quantityPicturesClose: Int,
        val selectableWithoutProgramming: Int,
        val referencePoint: String?,
        val order: Int,
        val status: String,
        val createdAt: String,
        val updatedAt: String,
        val deletedAt: String?,
        val specialWarning: String?,
        val executions: List<Execution> = emptyList(),
    )

    data class Execution(
        val id: Int,
        val siteExecutionId: Int,
        val positionId: Int,
        val ciltId: Int,
        val ciltSecuenceId: Int,
        val levelId: Int,
        val route: String?,
        val userId: Int,
        val userWhoExecutedId: Int,
        val secuenceSchedule: String,
        val allowExecuteBefore: Boolean,
        val allowExecuteBeforeMinutes: Int,
        val toleranceBeforeMinutes: Int,
        val toleranceAfterMinutes: Int,
        val allowExecuteAfterDue: Boolean,
        val secuenceStart: String?,
        val secuenceStop: String?,
        val duration: Int,
        val realDuration: String?,
        val standardOk: String,
        val initialParameter: String?,
        val evidenceAtCreation: Boolean,
        val finalParameter: String?,
        val evidenceAtFinal: Boolean,
        val nok: Boolean,
        val stoppageReason: Boolean,
        val machineStopped: Boolean,
        val status: String,
        val createdAt: String,
        val updatedAt: String,
        val deletedAt: String?,
        val referenceOpl: Opl,
        val remediationOpl: Opl,
    )

    data class Opl(
        val id: Int,
        val title: String,
        val objetive: String,
        val creatorName: String,
        val reviewerName: String,
        val oplType: String,
        val ciltUsageCount: Int,
        val lastUsedAt: String,
    )

    companion object {
        fun mockData(): ProcedimientoCiltData =
            ProcedimientoCiltData(
                positions =
                    listOf(
                        Position(
                            id = 25,
                            name = "Posicion operador de revolvedora IH",
                            siteName = "Universal Develop",
                            areaName = "Procesos",
                            ciltMasters =
                                listOf(
                                    CiltMaster(
                                        id = 76,
                                        siteId = 1,
                                        ciltName = "CILT IH",
                                        ciltDescription = "formato estandarizado de ejecución operativa en mantenimiento autónomo",
                                        creatorId = 178,
                                        creatorName = "Immanuel Diaz",
                                        reviewerId = 178,
                                        reviewerName = "Immanuel Diaz",
                                        approvedById = 92,
                                        approvedByName = "Erick",
                                        ciltDueDate = "2026-01-01T00:00:00.000Z",
                                        standardTime = 0,
                                        urlImgLayout = null,
                                        order = 1,
                                        dateOfLastUsed = "2025-06-23T19:32:45.000Z",
                                        createdAt = "2025-06-09T00:19:34.000Z",
                                        updatedAt = "2025-06-23T19:33:55.000Z",
                                        deletedAt = null,
                                        status = "A",
                                        sequences =
                                            listOf(
                                                Sequence(
                                                    id = 157,
                                                    siteId = 1,
                                                    siteName = "",
                                                    ciltMstrId = 76,
                                                    ciltMstrName = "CILT IH",
                                                    frecuencyId = 1,
                                                    frecuencyCode = "IT",
                                                    ciltTypeId = 1,
                                                    ciltTypeName = "Limpieza",
                                                    secuenceList = "Inspección de buen funcionamiento de la unidad",
                                                    secuenceColor = "00ccff",
                                                    toolsRequired = "Visual",
                                                    standardTime = 0,
                                                    standardOk = "Informes completos",
                                                    referenceOplSopId = 39,
                                                    remediationOplSopId = 45,
                                                    stoppageReason = 0,
                                                    machineStopped = 0,
                                                    quantityPicturesCreate = 1,
                                                    quantityPicturesClose = 1,
                                                    selectableWithoutProgramming = 0,
                                                    referencePoint = "1",
                                                    order = 1,
                                                    status = "A",
                                                    createdAt = "2025-06-09T00:24:19.000Z",
                                                    updatedAt = "2025-08-15T19:07:16.000Z",
                                                    deletedAt = null,
                                                    specialWarning = null,
                                                    executions = emptyList(),
                                                ),
                                            ),
                                    ),
                                ),
                        ),
                    ),
            )
    }
}
