package com.ih.osm.domain.model

data class SequenceExecutionData(
    val executionInfo: ExecutionInfo,
)

data class ExecutionInfo(
    val id: Int,
    val siteId: Int,
    val positionId: Int,
    val ciltId: Int,
    val ciltSecuenceId: Int,
    val levelId: Int,
    val route: String,
    val userId: Int,
    val userWhiExecutedId: Int,
    val secuenceSchedule: String,
    val secuenceStart: String,
    val secuenceStop: String,
    val duration: Int,
    val realDuration: Int,
    val standardOk: String,
    val initialParameter: String,
    val evidenceAtCreation: Int,
    val finalParameter: String,
    val evidenceAtFinal: Int,
    val nok: Int,
    val stoppageReason: Int,
    val machineStopped: Int,
    val amTagId: Int,
    val referencePoint: String,
    val secuenceList: String,
    val secuenceColor: String,
    val ciltSecuenciesExecutionscol: Int,
    val ciltTypeId: Int,
    val ciltTypeName: String,
    val referenceOplSopId: Int,
    val remediationOplSopId: String,
    val toolsRequiered: String,
    val selectableWithoutProgramming: Int,
    val status: String,
    val createdAt: String,
    val updatedAt: String,
    val deletedAt: String,
)
