package com.ih.m2.ui.utils

const val EMPTY = ""

const val ALL_OPEN_CARDS = "ALL_OPEN_CARDS"
const val MY_OPEN_CARDS = "MY_OPEN_CARDS"
const val ASSIGNED_CARDS = "ASSIGNED_CARDS"
const val UNASSIGNED_CARDS = "UNASSIGNED_CARDS"
const val EXPIRED_CARDS = "EXPIRED_CARDS"
const val CLOSED_CARDS = "CLOSED_CARDS"
const val CLEAN_FILTERS = "CLEAN_FILTERS"
const val STATUS_A = "A"
const val STATUS_P = "P"
const val STATUS_V = "V"
const val STATUS_R = "R"
const val STATUS_C = "C"
const val LOAD_CATALOGS = "load_catalogs"
const val IMG_CREATION = "IMCR"
const val IMG_CLOSE = "IMCL"
const val AUDIO_CREATION = "AUCR"
const val AUDIO_CLOSE = "AUCL"
const val STORED_REMOTE = "stored_network"
const val CARD_MAINTENANCE = "Mantenimiento"
const val PROVISIONAL_SOLUTION = "provisional_solution"
const val DEFINITIVE_SOLUTION = "definitive_solution"
const val VIDEO_CREATION = "VICR"
const val VIDEO_CLOSE = "VICL"